spring.application.name=sme-ticket-api

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sme_ticket_db
spring.datasource.username=postgres
spring.datasource.password=password

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Database initialisation
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# File handling
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/sme-ticket-realm